-- Select a plant
SELECT P.ID AS PLANT_ID,
    P.DESCRIPTION AS PLANT_DESCRIPTION,
    PG.ID AS PLANT_GROUP_ID,
    PG.NAME AS PLANT_GROUP_NAME,
    PG.DESCRIPTION AS PLANT_GROUP_DESCRIPTION
FROM PLANT P
    LEFT JOIN PLANT_GROUP PG on P.ID = PG.ID;

-- Select all plant IDs
SELECT ID
FROM PLANT;
