-- Select a sensor
SELECT S.ID AS SENSOR_ID,
       S.PLANT AS PLANT_ID,
       S.INTERVAL AS INTERVAL,
       ST.ID AS SENSOR_TYPE_ID,
       ST.NAME AS SENSOR_TYPE_NAME,
       ST.UNIT AS SENSOR_TYPE_UNIT
FROM SENSOR S
LEFT JOIN SENSOR_TYPE ST;
