-- Select a sensor
SELECT S.ID AS SENSOR_ID,
       S.PLANT AS PLANT_ID,
       S.INTERVAL AS INTERVAL,
       ST.ID AS SENSOR_TYPE_ID,
       ST.NAME AS SENSOR_TYPE_NAME,
       ST.UNIT AS SENSOR_TYPE_UNIT
FROM SENSOR S
LEFT JOIN SENSOR_TYPE ST
WHERE SENSOR_ID = ?;

-- Select all sensor IDs
SELECT ID FROM SENSOR;

-- Select a sensor Type
SELECT NAME, UNIT
    FROM SENSOR_TYPE
    WHERE ID = ?;

-- Select all sensor Type IDs
SELECT NAME, UNIT FROM SENSOR_TYPE;
