openapi: 3.0.0

info:
    title: PlantBuddy Server
    description: The backend for PlantBuddy.
    version: 1.0.0

servers:
    - url: http://localhost:5000/v1
      description: Local server

paths:
    /sensor-data:
        get:
            summary: Returns sensor data
            description: Returns sensor data.
            operationId: getSensorData

            parameters:
                - name: sensorId
                  in: query
                  description: ID of the sensor
                  required: true
                  schema:
                      type: integer

                - name: plantId
                  in: query
                  description: ID of the plant
                  required: true
                  schema:
                      type: integer

                - name: from
                  in: query
                  description: Start of the time range. Default to 24 hours ago.
                  required: false
                  schema:
                      type: string
                      format: date-time

                - name: to
                  in: query
                  description: End of the time range. Default to now.
                  required: false
                  schema:
                      type: string
                      format: date-time

            responses:
                "200":
                    description: An array of sensor data
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: "#/components/schemas/SensorData"

        post:
            summary: Adds sensor data
            description: Adds sensor data.
            operationId: addSensorData

            requestBody:
                description: Sensor data to add
                required: true
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/SensorDataPost"

            responses:
                "200":
                    description: Sensor data added
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/SensorData"

                "400":
                    description: Invalid sensor data
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    message:
                                        type: string
                                        example: "Invalid sensor data"

    /sensors:
        get:
            summary: Returns all sensor IDs
            description: Returns all sensor IDs.
            operationId: getSensors

            responses:
                "200":
                    description: An array of sensor IDs
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/SensorIds"

    /sensor/{id}:
        get:
            summary: Returns a sensor
            description: Returns a sensor.
            operationId: getSensor

            parameters:
                - name: id
                  in: path
                  description: ID of the sensor
                  required: true
                  schema:
                      type: integer

            responses:
                "200":
                    description: A sensor
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Sensor"

                "404":
                    description: Sensor not found
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    message:
                                        type: string
                                        example: "Sensor not found"

    /sensor-types:
        get:
            summary: Returns all sensor type IDs
            description: Returns all sensor type IDs.
            operationId: getSensorTypes

            responses:
                "200":
                    description: An array of sensor type IDs
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/SensorTypes"

    /sensor-type/{id}:
        get:
            summary: Returns a sensor type
            description: Returns a sensor type.
            operationId: getSensorType

            parameters:
                - name: id
                  in: path
                  description: ID of the sensor type
                  required: true
                  schema:
                      type: integer

            responses:
                "200":
                    description: A sensor type
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/SensorType"

                "404":
                    description: Sensor type not found
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    message:
                                        type: string
                                        example: "Sensor type not found"

    /plants:
        get:
            summary: Returns all plants
            description: Returns all plants.
            operationId: getPlants

            parameters:
                - name: plantGroupId
                  in: query
                  description: ID of the plant
                  required: false
                  schema:
                      type: integer

            responses:
                "200":
                    description: An array of plants
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/PlantIds"

    /plant/{id}:
        get:
            summary: Returns a plant
            description: Returns a plant.
            operationId: getPlant

            parameters:
                - name: id
                  in: path
                  description: ID of the plant
                  required: true
                  schema:
                      type: integer

            responses:
                "200":
                    description: A plant
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Plant"

                "404":
                    description: Plant not found
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    message:
                                        type: string
                                        example: "Plant not found"

    /plant-groups:
        get:
            summary: Returns all plant groups
            description: Returns all plant groups.
            operationId: getPlantGroups

            responses:
                "200":
                    description: An array of plant groups
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/PlantGroupIds"

    /plant-group/{id}:
        get:
            summary: Returns a plant group
            description: Returns a plant group.
            operationId: getPlantGroup

            parameters:
                - name: id
                  in: path
                  description: ID of the plant group
                  required: true
                  schema:
                      type: integer

            responses:
                "200":
                    description: A plant group
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/PlantGroup"

                "404":
                    description: Plant group not found
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    message:
                                        type: string
                                        example: "Plant group not found"

    /plant-ql:
        get:
            summary: Returns plants based on a query
            description: Returns plants based on a query.
            operationId: getPlantsQL

            parameters:
                - name: query
                  in: query
                  description: Query to execute
                  required: true

                  schema:
                      type: string

            responses:
                "200":
                    description: An array of plants
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: "#/components/schemas/Plant"

                "400":
                    description: Invalid query
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    message:
                                        type: string
                                        example: "Invalid query"

components:
    schemas:
        SensorData:
            type: object
            description: Data collected by a sensor.

            required:
                - "id"
                - "sensor"
                - "value"
                - "timestamp"

            properties:
                id:
                    type: integer
                    description: ID of the data set.
                    example: 1

                sensor:
                    type: integer
                    description: ID of the sensor that collected the data.
                    example: 1

                value:
                    type: number
                    description: Value collected by the sensor.
                    example: 1.5

                timestamp:
                    type: string
                    format: date-time
                    description: Timestamp of the data.
                    example: "2020-01-01T00:00:00.000Z"

        SensorDataPost:
            type: object
            description: Data collected by a sensor.

            required:
                - "sensor"
                - "value"
                - "timestamp"

            properties:
                sensor:
                    type: integer
                    description: ID of the sensor that collected the data.
                    example: 1

                value:
                    type: number
                    description: Value collected by the sensor.
                    example: 1.5

                timestamp:
                    type: string
                    description: Timestamp of the data.
                    example: "2020-01-01T00:00:00.000Z"

        SensorIds:
            type: object
            description: An array of sensor IDs.

            required:
                - "sensors"

            properties:
                sensors:
                    type: array
                    description: An array of sensor IDs.
                    items:
                        type: integer
                        example: [1]

        Sensor:
            type: object
            description: A sensor that collects data.

            required:
                - "id"
                - "plant"
                - "type"
                - "interval"

            properties:
                id:
                    type: integer
                    description: ID of the sensor.
                    example: 1

                plant:
                    type: integer
                    description: ID of the Plant the sensor monitors.
                    example: 1

                type:
                    description: Type of the sensor.
                    $ref: "#/components/schemas/SensorType"

                interval:
                    type: integer
                    description: Interval in seconds at which the sensor collects data.
                    example: 50

        Plant:
            type: object
            description: A plant.

            required:
                - "id"
                - "group"

            properties:
                id:
                    type: integer
                    description: ID of the plant.
                    example: 1

                description:
                    type: string
                    description: An optional description.
                    example: "The big one behind the door"

                group:
                    description: Plant group of the plant.
                    $ref: "#/components/schemas/PlantGroup"

                additionalCareTips:
                    type: array
                    description: Optional additional care tips.

                    items:
                        type: string
                        example: ["Massage every morning"]

        PlantIds:
            type: object
            description: An array of plant IDs.

            required:
                - "plants"

            properties:
                plants:
                    type: array
                    description: An array of plant IDs.
                    items:
                        type: integer
                        example: [1]

        PlantGroup:
            type: object
            description: A group of plants of the same type.

            required:
                - "id"
                - "type"
                - "ranges"

            properties:
                id:
                    type: integer
                    example: 1

                name:
                    type: string
                    description: Type of the plant group.
                    example: "Cactaceae"

                description:
                    type: string
                    description: An optional description.
                    example: "The big one behind the door"

                careTips:
                    type: array
                    description: Optional care tips.

                    items:
                        type: string
                        example:
                            - "Play Mozart music every evening"
                            - "Place in the sun"

                ranges:
                    type: array
                    description: Ranges of values to be interpreted as normal for the sensors of the plant group.

                    items:
                        $ref: "#/components/schemas/SensorRange"

        PlantGroupIds:
            type: object
            description: An array of plant group IDs.

            required:
                - "plantGroups"

            properties:
                plantGroups:
                    type: array
                    description: An array of plant group IDs.
                    items:
                        type: integer
                        example: [1]

        SensorRange:
            type: object
            description: Range of values to be interpreted as normal for a sensor.

            required:
                - "type"
                - "min"
                - "max"

            properties:
                type:
                    description: Type of the sensor.
                    $ref: "#/components/schemas/SensorType"

                min:
                    type: number
                    description: Minimum value of the range (inclusive).
                    example: 20

                max:
                    type: number
                    description: Maximum value of the range (inclusive).
                    example: 80

        SensorType:
            type: object
            description: Type of sensor.

            required:
                - "name"
                - "unit"

            properties:
                name:
                    type: string
                    description: Name of the sensor type.
                    example: "humidity"

                unit:
                    type: string
                    description: Unit of the sensor type.
                    example: "percent"

        SensorTypes:
            type: object
            description: An array of sensor type IDs.

            required:
                - "types"

            properties:
                types:
                    type: array
                    description: An array of sensor type IDs.
                    items:
                        type: integer
                        example: [1]

        PlantQL:
            type: object
            description: Plant Query Language result.

            required:
                - "query"
                - "data"

            properties:
                query:
                    type: string
                    description: The query that was executed.
                    example: 'Sensor.type="humidity" & Data.value > 50 & Plant.type="Cactaceae"'

                data:
                    type: array
                    description: The result of the query.

                    items:
                        $ref: "#/components/schemas/Plant"
