### Get sensor data sets.
GET http://localhost:3333/v1/sensor-data?sensor=humidity&plant=1&from=2019-01-01T00:00:00.000Z&to=2023-05-20T00:00:00.000Z
Authorization: Basic dGVzdHVzZXI6MTIzNA==

### Save a new sensor data set.
POST http://localhost:3333/v1/sensor-data
Content-Type: application/json

{
    "data": [
        {
            "controller": "fbf30c62-ce17-45fc-a596-42bc33d11758",
            "sensor": "temperature",
            "value": 20.7
        }
    ]
}


### Get a single plant.
GET http://localhost:3333/v1/plant/3
Authorization: Basic dGVzdHVzZXI6MTIzNA==

### Create a new plant.
POST http://localhost:3333/v1/plant
Authorization: Basic dGVzdHVzZXI6MTIzNA==
Content-Type: application/json

{
    "name": "testplant-3",
    "description": "testplant",
    "plantGroupId": 1,
    "Species": "Test Plant",
    "Location": "Das andere Fenster",
    "additionalCareTips": ["Wasser geben", "Düngen"]
}

### Update a plant.
PUT http://localhost:3333/v1/plant/3
Authorization: Basic dGVzdHVzZXI6MTIzNA==
Content-Type: application/json

{
    "name": "testplant-3",
    "description": "testplant that has been modified",
    "plantGroupId": 1,
    "Species": "Test Plant",
    "Location": "Das andere Fenster",
    "additionalCareTips": ["Wasser geben", "Düngen", "Liebe geben"]
}

### Delete a plant.
DELETE http://localhost:3333/v1/plant/4
Authorization: Basic dGVzdHVzZXI6MTIzNA==


### Get all plant IDs.
GET http://localhost:3333/v1/plants


### Get all plants in a plant group.
GET http://localhost:3333/v1/plants?plantGroupId=1
Authorization: Basic dGVzdHVzZXI6MTIzNA==

### Get a single plant group.
GET http://localhost:3333/v1/plant-group/1
Authorization: Basic dGVzdHVzZXI6MTIzNA==

### Create a plant group.
POST http://localhost:3333/v1/plant-group
Authorization: Basic dGVzdHVzZXI6MTIzNA==

{
    "name": "Cactaceae",
    "description": "Mein kleiner grüner Kaktus",
    "careTips": ["Bene stinkt"],
    "sensorRanges": [
        {
            "sensorType": {
                "name": "humidity",
                "unit": "percent"
            },
            "min": 40,
            "max": 60
        }
    ]
}

### Update a plant group.
PUT http://localhost:3333/v1/plant-group/1
Authorization: Basic dGVzdHVzZXI6MTIzNA==

{
    "name": "Cactaceae",
    "description": "Mein kleiner grüner Kaktus",
    "careTips": ["Bene stinkt nicht mehr"],
    "sensorRanges": [
        {
            "sensorType": {
                "name": "humidity",
                "unit": "percent"
            },
            "min": 40,
            "max": 60
        }
    ]
}

### Delete a plant group.
DELETE http://localhost:3333/v1/plant-group/1
Authorization: Basic dGVzdHVzZXI6MTIzNA==


### Get all plant group IDs.
GET http://localhost:3333/v1/plant-groups
Authorization: Basic dGVzdHVzZXI6MTIzNA==


### Get all sensor types.
GET http://localhost:3333/v1/sensor-types
Authorization: Basic dGVzdHVzZXI6MTIzNA==


### Get a single controller.
GET http://localhost:3333/v1/controller/fbf30c62-ce17-45fc-a596-42bc33d11758
Authorization: Basic dGVzdHVzZXI6MTIzNA==


### Login a user. Returns the corresponding user.
GET http://localhost:3333/v1/user/login
Authorization: Basic dGVzdHVzZXI6MTIzNA==


### Get all users.
GET http://localhost:3333/v1/users
Authorization: Basic cm9vdDoxMjM0


### Get a single user.
GET http://localhost:3333/v1/user/7
Authorization: Basic cm9vdDoxMjM0

### Create a new user.
POST http://localhost:3333/v1/user/
Authorization: Basic cm9vdDoxMjM0
Content-Type: application/json

{
    "name": "testuser42",
    "password": "1234",
    "role": 1
}

### Update a user.
PUT http://localhost:3333/v1/user/7
Authorization: Basic cm9vdDoxMjM0
Content-Type: application/json

{
    "name": "testuser42",
    "password": "123456",
    "role": 1
}

### Delete a user.
DELETE http://localhost:3333/v1/user/7
Authorization: Basic cm9vdDoxMjM0
