openapi: 3.0.0

info:
    title: PlantBuddy Server
    description: The backend for PlantBuddy.
    version: 1.0.0

servers:
    -   url: http://localhost:5000/v1
        description: Local server

paths:
    /hello:
        get:
            summary: Returns hello world
            description: Just a first endpoint
            operationId: hello
            responses:
                '200':
                    description: A string containing hello world
                    content:
                        plain/text:
                            schema:
                                type: string
                                example: hello, world
